/**
 * Lucide icons — default Orbit icon style (UI chrome, nav, devtools).
 * Import from `@manovaspace/ui` only — not `lucide-react` in apps.
 */
export {
  ArrowLeft as ArrowLeftIcon,
  ArrowLeftRight as ArrowsRightLeftIcon,
  ArrowRight as ArrowRightIcon,
  Box as CubeIcon,
  Calendar as CalendarIcon,
  Check as CheckIcon,
  ChevronDown as ChevronDownIcon,
  ChevronRight as ChevronRightIcon,
  ChevronsUpDown as ChevronUpDownIcon,
  Clipboard as ClipboardDocumentIcon,
  ClipboardList as ClipboardDocumentListIcon,
  Cpu as CpuChipIcon,
  ExternalLink as ExternalLinkIcon,
  Globe as GlobeAltIcon,
  GraduationCap as AcademicCapIcon,
  Home as HomeIcon,
  Info as InformationCircleIcon,
  Layers as RectangleStackIcon,
  ListFilter as FunnelIcon,
  LogOut as ArrowRightOnRectangleIcon,
  Mail as MailIcon,
  Monitor as ComputerDesktopIcon,
  Moon as MoonIcon,
  Paintbrush as PaintBrushIcon,
  Palette as SwatchIcon,
  Plus as PlusIcon,
  Puzzle as PuzzlePieceIcon,
  Scale as ScaleIcon,
  Search as MagnifyingGlassIcon,
  Settings as Cog6ToothIcon,
  SkipForward as SkipForwardIcon,
  Smartphone as DevicePhoneMobileIcon,
  Sun as SunIcon,
  Wrench as WrenchScrewdriverIcon,
  X as XMarkIcon,
  Zap as BoltIcon,
} from "lucide-react";
