/**
 * Lucide icons — default Orbit icon style (UI chrome, nav, devtools).
 * Import from `@manovaspace/ui` only — not `lucide-react` in apps.
 */
export {
  AlertTriangle as AlertTriangleIcon,
  ArrowDownToLine as ArrowDownTrayIcon,
  ArrowLeft as ArrowLeftIcon,
  ArrowLeftRight as ArrowsRightLeftIcon,
  ArrowRight as ArrowRightIcon,
  ArrowUpFromLine as ArrowUpTrayIcon,
  Box as CubeIcon,
  Building2 as BuildingOffice2Icon,
  Calendar as CalendarIcon,
  Check as CheckIcon,
  ChevronDown as ChevronDownIcon,
  ChevronRight as ChevronRightIcon,
  ChevronsUpDown as ChevronUpDownIcon,
  Clipboard as ClipboardDocumentIcon,
  ClipboardList as ClipboardDocumentListIcon,
  CornerDownRight as CornerDownRightIcon,
  Cpu as CpuChipIcon,
  ExternalLink as ExternalLinkIcon,
  Folder as FolderIcon,
  Globe as GlobeAltIcon,
  GraduationCap as AcademicCapIcon,
  Home as HomeIcon,
  Info as InformationCircleIcon,
  Layers as RectangleStackIcon,
  ListFilter as FunnelIcon,
  Lock as LockIcon,
  LogOut as ArrowRightOnRectangleIcon,
  Mail as MailIcon,
  Menu as Bars3Icon,
  Menu as MenuIcon,
  MessageCircle as ChatBubbleLeftIcon,
  Monitor as ComputerDesktopIcon,
  Moon as MoonIcon,
  Package as PackageIcon,
  Paintbrush as PaintBrushIcon,
  Palette as SwatchIcon,
  Plus as PlusIcon,
  Puzzle as PuzzlePieceIcon,
  Refrigerator as RefrigeratorIcon,
  Scale as ScaleIcon,
  Search as MagnifyingGlassIcon,
  Settings as Cog6ToothIcon,
  SkipForward as SkipForwardIcon,
  Smartphone as DevicePhoneMobileIcon,
  Snowflake as SnowflakeIcon,
  Sun as SunIcon,
  Tag as TagIcon,
  Trash2 as TrashIcon,
  Wrench as WrenchScrewdriverIcon,
  X as XMarkIcon,
  Zap as BoltIcon,
} from "lucide-react";
